name: Build via autotools
run-name: ${{ github.actor }} is building and testing via autotools
on: [push]
jobs:
  Build-via-cmake-msvc:
    runs-on: windows-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: cmake & cmake --build
        shell: pwsh
        run: |
          mkdir .\Work
          cd .\Work
          cmake.exe ..
          cmake.exe --build .
          cd ..
      - name: test
        shell: bash
        run: |
          cd ./Work
          export bindir=./Debug/bin exeext=.ext srcdir=../source
          $srcdir/testdata/gha_sb-test.sh
      - run: echo "ğŸ This job's status is ${{ job.status }}."
