name: Build via autotools
run-name: ${{ github.actor }} is building and testing via autotools
on: [push]
jobs:
  Build-via-autotools:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: configure & make
        run: |
          ls ${{ github.workspace }}
          mkdir ./Work
          cd ./Work
          ../source/configure
          make
          make check
      - run: echo "ğŸ This job's status is ${{ job.status }}."
