name: Build on MACOS
run-name: ${{ github.actor }} is building and testing on macos
on:
  push:
    branches:
      - 'master'
      - 'work*'
      - 'build/*'
jobs:
  Build-via-autotools:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: check version of tools
        shell: bash
        run: |
          bash --version
          gcc --version
          perl --version
          python --version
          python3 --version
          ruby --version
#      - name: brew
#        shell: bash
#        run: |
#          brew install icu4c
      - name: configure & make
        shell: bash
        run: |
          pwd
          ls .
          mkdir ./Work
          cd ./Work
          find /usr/local -name icudataver.h 2> /dev/null
          find /usr/local -name icudataver.h
          find /usr -name icudataver.h 2> /dev/null
          ICU_PREFIX=`find /usr/local -name icudataver.h | sed -e 's/\/include\/unicode\/icudataver.h//'`
          echo "ICU_PREFIX: " $ICU_PREFIX
          ls -lR $ICU_PREFIX/include
          ls -lR $ICU_PREFIX/lib
          PKG_CONFIG_PATH=$ICU_PREFIX/lib/pkgconfig pkg-config --libs --cflags icu-uc icu-io
          gcc -o gha_sb ../source/gha_sb.c -I$ICU_PREFIX/include -L$ICU_PREFIX/lib -licuio -licui18n -licuuc -licudata
          ./gha_sb --version
          ./gha_sb --icuversion
          ./gha_sb
          ../source/configure CFLAGS=-I/usr/local/Cellar/icu4c/73.2/include LDFLAGS=-L/usr/local/Cellar/icu4c/73.2/lib
          make
          echo "make: done"
#          gcc -o gha_sb ../source/gha_sb.c
#          CFLAGS=-I/usr/local/opt/icu4c/include LDFLAGS=-L/usr/local/opt/icu4c/lib gcc -o gha_sb -licuuc
      - name: test
        shell: bash
        run: |
          cd ./Work
          ./gha_sb --version
          ./gha_sb --icuversion
          make check
        env:
          TESTENV: "foo:bar; baz"
      - run: echo "â›„ This job's status is ${{ job.status }}."
